### ISSUE TITLE
Implement a front-end build process

### ISSUE THREAD

**Issue by cizmic** [circlestorm/sockchat#57]
Perhaps slap on Grunt.js to automate (S)CSS/JS compiling, linting, packaging, compressing, etc. It will allow us to achieve ***ENTERPRISE QUALITY MAINTAINABILITY***.

I'm planning to implement this myself with a PR, unless anyone has objections.

**Comment by MallocNull** [comment]
If you could write up something that would do that, I'd appreciate it. I don't have a lot of experience with front-end compilation.

**Comment by cizmic** [comment]
Sure thing, working on it right now.
